"""Auto-migration 1781968617

Revision ID: 31d488c3b4bd
Revises: 
Create Date: 2026-06-20 17:16:57.703448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31d488c3b4bd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pomiary_PomiarId'), table_name='pomiary')
    op.drop_table('pomiary')
    op.drop_index(op.f('ix_poradnik_PoradnikId'), table_name='poradnik')
    op.drop_table('poradnik')
    op.drop_index(op.f('ix_users_UserId'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('UserId', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('avatar_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('UserId', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_UserId'), 'users', ['UserId'], unique=False)
    op.create_table('poradnik',
    sa.Column('PoradnikId', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('kategoria', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('tytul', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('tresc', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('PoradnikId', name=op.f('poradnik_pkey'))
    )
    op.create_index(op.f('ix_poradnik_PoradnikId'), 'poradnik', ['PoradnikId'], unique=False)
    op.create_table('pomiary',
    sa.Column('PomiarId', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tabele_pomiarowe_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data_pomiaru', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('temperatura', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('godzina_pomiaru', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('informacje_dodatkowe', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('dzien_cyklu', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('przyjmowanie_progesteronu', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('okres', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('krwawienie_plamienie_brudzenie', sa.VARCHAR(), server_default=sa.text("'BRAK'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('PomiarId', name=op.f('pomiary_pkey'))
    )
    op.create_index(op.f('ix_pomiary_PomiarId'), 'pomiary', ['PomiarId'], unique=False)
    # ### end Alembic commands ###
