"""Auto-migration 1781518091

Revision ID: 650fb7f37c98
Revises: 
Create Date: 2026-06-15 12:08:11.549637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '650fb7f37c98'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poradnik',
    sa.Column('PoradnikId', sa.Integer(), nullable=False),
    sa.Column('kategoria', sa.String(length=50), nullable=False),
    sa.Column('tytul', sa.String(length=100), nullable=False),
    sa.Column('tresc', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('PoradnikId')
    )
    op.create_index(op.f('ix_poradnik_PoradnikId'), 'poradnik', ['PoradnikId'], unique=False)
    op.create_table('users',
    sa.Column('UserId', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('UserId')
    )
    op.create_index(op.f('ix_users_UserId'), 'users', ['UserId'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('tabele_pomiarowe',
    sa.Column('TabelaPomiarowaId', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('user_id_udostepnione', sa.Integer(), nullable=True),
    sa.Column('imie_i_nazwisko', sa.String(length=100), nullable=True),
    sa.Column('wiek', sa.Integer(), nullable=True),
    sa.Column('godzina_pomiaru', sa.Time(), nullable=True),
    sa.Column('rok', sa.Integer(), nullable=True),
    sa.Column('numer_cyklu', sa.Integer(), nullable=True),
    sa.Column('pierwszy_dzien_miesiaczki', sa.Integer(), nullable=True),
    sa.Column('dlugosc_cyklu', sa.Integer(), nullable=True),
    sa.Column('dlugosc_fazy_lutealnej', sa.Integer(), nullable=True),
    sa.Column('informacje_dodatkowe', sa.String(length=255), nullable=True),
    sa.Column('koniec_cyklu', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.UserId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('TabelaPomiarowaId')
    )
    op.create_index(op.f('ix_tabele_pomiarowe_TabelaPomiarowaId'), 'tabele_pomiarowe', ['TabelaPomiarowaId'], unique=False)
    op.create_table('pomiary',
    sa.Column('PomiarId', sa.Integer(), nullable=False),
    sa.Column('tabele_pomiarowe_id', sa.Integer(), nullable=False),
    sa.Column('data_pomiaru', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('temperatura', sa.Float(), nullable=False),
    sa.Column('godzina_pomiaru', sa.Time(), nullable=False),
    sa.Column('informacje_dodatkowe', sa.String(length=255), nullable=True),
    sa.Column('dzien_cyklu', sa.Integer(), nullable=True),
    sa.Column('przyjmowanie_progesteronu', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('okres', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('krwawienie_plamienie_brudzenie', sa.String(), server_default='BRAK', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tabele_pomiarowe_id'], ['tabele_pomiarowe.TabelaPomiarowaId'], ),
    sa.PrimaryKeyConstraint('PomiarId')
    )
    op.create_index(op.f('ix_pomiary_PomiarId'), 'pomiary', ['PomiarId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pomiary_PomiarId'), table_name='pomiary')
    op.drop_table('pomiary')
    op.drop_index(op.f('ix_tabele_pomiarowe_TabelaPomiarowaId'), table_name='tabele_pomiarowe')
    op.drop_table('tabele_pomiarowe')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_UserId'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_poradnik_PoradnikId'), table_name='poradnik')
    op.drop_table('poradnik')
    # ### end Alembic commands ###
