"""Auto-migration 1781708956

Revision ID: 8f3ee77ec3fc
Revises: 650fb7f37c98
Create Date: 2026-06-17 17:09:16.770166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f3ee77ec3fc'
down_revision: Union[str, Sequence[str], None] = '650fb7f37c98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
