"""Auto-migration 1781709348

Revision ID: d39f5ed6626b
Revises: 8f3ee77ec3fc
Create Date: 2026-06-17 17:15:48.442583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd39f5ed6626b'
down_revision: Union[str, Sequence[str], None] = '8f3ee77ec3fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
