"""Initial migration

Revision ID: a29c5ffd3c19
Revises: 15c3247891f6
Create Date: 2026-06-14 16:13:20.447227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a29c5ffd3c19'
down_revision: Union[str, Sequence[str], None] = '15c3247891f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pomiary', sa.Column('okres', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.alter_column('tabela_pomiaru', 'imie_i_nazwisko',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('tabela_pomiaru', 'wiek',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tabela_pomiaru', 'godzina_pomiaru',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('tabela_pomiaru', 'rok',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tabela_pomiaru', 'numer_cyklu',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tabela_pomiaru', 'pierwszy_dzien_miesiaczki',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tabela_pomiaru', 'dlugosc_cyklu',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tabela_pomiaru', 'dlugosc_fazy_lutealnej',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tabela_pomiaru', 'dlugosc_fazy_lutealnej',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tabela_pomiaru', 'dlugosc_cyklu',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tabela_pomiaru', 'pierwszy_dzien_miesiaczki',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tabela_pomiaru', 'numer_cyklu',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tabela_pomiaru', 'rok',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tabela_pomiaru', 'godzina_pomiaru',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('tabela_pomiaru', 'wiek',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tabela_pomiaru', 'imie_i_nazwisko',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('pomiary', 'okres')
    # ### end Alembic commands ###
