"""Auto-migration 1781510631

Revision ID: ab51a4e8dd42
Revises: 36d8f93fc422
Create Date: 2026-06-15 10:03:51.979479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab51a4e8dd42'
down_revision: Union[str, Sequence[str], None] = '36d8f93fc422'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
