"""Initial migration

Revision ID: b55d1eaff863
Revises: a29c5ffd3c19
Create Date: 2026-06-14 16:46:11.834350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b55d1eaff863'
down_revision: Union[str, Sequence[str], None] = 'a29c5ffd3c19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pomiary', 'data_pomiaru',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('pomiary', 'dzien_cyklu',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pomiary', 'przyjmowanie_progesteronu',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('pomiary', 'krwawienie_plamienie_brudzenie',
               existing_type=postgresql.ENUM('KRWAWIENIE', 'PLAMIENIE', 'BRUDZENIE', 'BRAK', name='typobjawukrwi'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pomiary', 'krwawienie_plamienie_brudzenie',
               existing_type=postgresql.ENUM('KRWAWIENIE', 'PLAMIENIE', 'BRUDZENIE', 'BRAK', name='typobjawukrwi'),
               nullable=False)
    op.alter_column('pomiary', 'przyjmowanie_progesteronu',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('pomiary', 'dzien_cyklu',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pomiary', 'data_pomiaru',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###
