"""Initial migration

Revision ID: c671bae32d2a
Revises: 9b381a283e01
Create Date: 2026-06-15 09:56:26.898341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c671bae32d2a'
down_revision: Union[str, Sequence[str], None] = '9b381a283e01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Poradnik',
    sa.Column('PoradnikId', sa.Integer(), nullable=False),
    sa.Column('kategoria', sa.String(length=50), nullable=False),
    sa.Column('tytul', sa.String(length=100), nullable=False),
    sa.Column('tresc', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('PoradnikId')
    )
    op.create_index(op.f('ix_Poradnik_PoradnikId'), 'Poradnik', ['PoradnikId'], unique=False)
    op.create_table('Users',
    sa.Column('UserId', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('UserId')
    )
    op.create_index(op.f('ix_Users_UserId'), 'Users', ['UserId'], unique=False)
    op.create_index(op.f('ix_Users_email'), 'Users', ['email'], unique=True)
    op.create_index(op.f('ix_Users_username'), 'Users', ['username'], unique=True)
    op.create_table('TabelePomiarowe',
    sa.Column('TabelaPomiarowaId', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('user_id_udostepnione', sa.Integer(), nullable=True),
    sa.Column('imie_i_nazwisko', sa.String(length=100), nullable=True),
    sa.Column('wiek', sa.Integer(), nullable=True),
    sa.Column('godzina_pomiaru', sa.Time(), nullable=True),
    sa.Column('rok', sa.Integer(), nullable=True),
    sa.Column('numer_cyklu', sa.Integer(), nullable=True),
    sa.Column('pierwszy_dzien_miesiaczki', sa.Integer(), nullable=True),
    sa.Column('dlugosc_cyklu', sa.Integer(), nullable=True),
    sa.Column('dlugosc_fazy_lutealnej', sa.Integer(), nullable=True),
    sa.Column('informacje_dodatkowe', sa.String(length=255), nullable=True),
    sa.Column('koniec_cyklu', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['Users.UserId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('TabelaPomiarowaId')
    )
    op.create_index(op.f('ix_TabelePomiarowe_TabelaPomiarowaId'), 'TabelePomiarowe', ['TabelaPomiarowaId'], unique=False)
    op.create_table('Pomiary',
    sa.Column('PomiarId', sa.Integer(), nullable=False),
    sa.Column('TabelePomiarowe_id', sa.Integer(), nullable=False),
    sa.Column('data_pomiaru', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('temperatura', sa.Float(), nullable=False),
    sa.Column('godzina_pomiaru', sa.Time(), nullable=False),
    sa.Column('informacje_dodatkowe', sa.String(length=255), nullable=True),
    sa.Column('dzien_cyklu', sa.Integer(), nullable=True),
    sa.Column('przyjmowanie_progesteronu', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('okres', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('krwawienie_plamienie_brudzenie', sa.Enum('KRWAWIENIE', 'PLAMIENIE', 'BRUDZENIE', 'BRAK', name='typobjawukrwi'), server_default='BRAK', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['TabelePomiarowe_id'], ['TabelePomiarowe.TabelaPomiarowaId'], ),
    sa.PrimaryKeyConstraint('PomiarId')
    )
    op.create_index(op.f('ix_Pomiary_PomiarId'), 'Pomiary', ['PomiarId'], unique=False)
    op.drop_index(op.f('ix_pomiary_PomiarId'), table_name='pomiary')
    op.drop_table('pomiary')
    op.drop_index(op.f('ix_poradnik_PoradnikId'), table_name='poradnik')
    op.drop_table('poradnik')
    op.drop_index(op.f('ix_tabela_pomiaru_TabelaPomiarowaId'), table_name='tabela_pomiaru')
    op.drop_table('tabela_pomiaru')
    op.drop_index(op.f('ix_users_UserId'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('UserId', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('avatar_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('UserId', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_UserId'), 'users', ['UserId'], unique=False)
    op.create_table('tabela_pomiaru',
    sa.Column('TabelaPomiarowaId', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id_udostepnione', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('imie_i_nazwisko', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('wiek', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('godzina_pomiaru', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('rok', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('numer_cyklu', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pierwszy_dzien_miesiaczki', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dlugosc_cyklu', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dlugosc_fazy_lutealnej', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('informacje_dodatkowe', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('koniec_cyklu', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.UserId'], name=op.f('tabela_pomiaru_owner_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('TabelaPomiarowaId', name=op.f('tabela_pomiaru_pkey'))
    )
    op.create_index(op.f('ix_tabela_pomiaru_TabelaPomiarowaId'), 'tabela_pomiaru', ['TabelaPomiarowaId'], unique=False)
    op.create_table('poradnik',
    sa.Column('PoradnikId', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('kategoria', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('tytul', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('tresc', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('PoradnikId', name=op.f('poradnik_pkey'))
    )
    op.create_index(op.f('ix_poradnik_PoradnikId'), 'poradnik', ['PoradnikId'], unique=False)
    op.create_table('pomiary',
    sa.Column('PomiarId', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tabela_pomiaru_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data_pomiaru', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('temperatura', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('godzina_pomiaru', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('informacje_dodatkowe', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('dzien_cyklu', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('przyjmowanie_progesteronu', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('okres', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tabela_pomiaru_id'], ['tabela_pomiaru.TabelaPomiarowaId'], name=op.f('pomiary_tabela_pomiaru_id_fkey')),
    sa.PrimaryKeyConstraint('PomiarId', name=op.f('pomiary_pkey'))
    )
    op.create_index(op.f('ix_pomiary_PomiarId'), 'pomiary', ['PomiarId'], unique=False)
    op.drop_index(op.f('ix_Pomiary_PomiarId'), table_name='Pomiary')
    op.drop_table('Pomiary')
    op.drop_index(op.f('ix_TabelePomiarowe_TabelaPomiarowaId'), table_name='TabelePomiarowe')
    op.drop_table('TabelePomiarowe')
    op.drop_index(op.f('ix_Users_username'), table_name='Users')
    op.drop_index(op.f('ix_Users_email'), table_name='Users')
    op.drop_index(op.f('ix_Users_UserId'), table_name='Users')
    op.drop_table('Users')
    op.drop_index(op.f('ix_Poradnik_PoradnikId'), table_name='Poradnik')
    op.drop_table('Poradnik')
    # ### end Alembic commands ###
